export const countries = [
  { id: 1, value: "ALGERIA", label: "الجزائر" },
  { id: 2, value: "BAHRAIN", label: "البحرين" },
  { id: 3, value: "COMOROS", label: "جزر القمر" },
  { id: 4, value: "DJIBOUTI", label: "جيبوتي" },
  { id: 5, value: "EGYPT", label: "مصر" },
  { id: 6, value: "IRAQ", label: "العراق" },
  { id: 7, value: "JORDAN", label: "الأردن" },
  { id: 8, value: "KUWAIT", label: "الكويت" },
  { id: 9, value: "LEBANON", label: "لبنان" },
  { id: 10, value: "LIBYA", label: "ليبيا" },
  { id: 11, value: "MAURITANIA", label: "موريتانيا" },
  { id: 12, value: "MOROCCO", label: "المغرب" },
  { id: 13, value: "OMAN", label: "عمان" },
  { id: 14, value: "PALESTINE", label: "فلسطين" },
  { id: 15, value: "QATAR", label: "قطر" },
  { id: 16, value: "SAUDI_ARABIA", label: "السعودية" },
  { id: 17, value: "SOMALIA", label: "الصومال" },
  { id: 18, value: "SUDAN", label: "السودان" },
  { id: 19, value: "SYRIA", label: "سوريا" },
  { id: 20, value: "TUNISIA", label: "تونس" },
  { id: 21, value: "UNITED_ARAB_EMIRATES", label: "الإمارات" },
  { id: 22, value: "YEMEN", label: "اليمن" },
  { id: 23, value: "AFGHANISTAN", label: "أفغانستان" },
  {
    id: 24,
    value: "UNITED_STATES_OF_AMERICA",
    label: "الولايات المتحدة الأمريكية",
  },
  { id: 25, value: "FRANCE", label: "فرنسا" },
  { id: 26, value: "CANADA", label: "كندا" },
  { id: 27, value: "UNITED_KINGDOM", label: "المملكة المتحدة" },
  { id: 28, value: "GERMANY", label: "ألمانيا" },
  { id: 29, value: "AUSTRALIA", label: "أستراليا" },
  { id: 30, value: "ITALY", label: "إيطاليا" },
  { id: 31, value: "SPAIN", label: "إسبانيا" },
  { id: 32, value: "NETHERLANDS", label: "هولندا" },
  { id: 33, value: "SWEDEN", label: "السويد" },
  { id: 34, value: "SWITZERLAND", label: "سويسرا" },
  { id: 35, value: "BELGIUM", label: "بلجيكا" },
  { id: 36, value: "RUSSIA", label: "روسيا" },
  { id: 37, value: "CHINA", label: "الصين" },
  { id: 38, value: "JAPAN", label: "اليابان" },
  { id: 39, value: "BRAZIL", label: "البرازيل" },
  { id: 40, value: "ARGENTINA", label: "الأرجنتين" },
  { id: 41, value: "TURKEY", label: "تركيا" },
  { id: 42, value: "MALAYSIA", label: "ماليزيا" },
  { id: 43, value: "DENMARK", label: "الدنمارك" },
  { id: 44, value: "NORWAY", label: "النرويج" },
  { id: 45, value: "AUSTRIA", label: "النمسا" },
  { id: 46, value: "GREECE", label: "اليونان" },
  { id: 47, value: "POLAND", label: "بولندا" },
  { id: 48, value: "HUNGARY", label: "المجر" },
  { id: 49, value: "PORTUGAL", label: "البرتغال" },
  { id: 50, value: "OTHER", label: "دولة أخرى" },
];
